name: Auto Label

on:
    pull_request:
        types: [opened, synchronize]

jobs:
    label:
        name: Auto Label PR
        runs-on: ubuntu-latest
        timeout-minutes: 5
        permissions:
            pull-requests: write

        steps:
            - name: Label PR
              uses: actions/labeler@v6
              with:
                  sync-labels: true
